name:                AOC2020
version:             0.1.0.0
github:              "tftio/AOC2020"
license:             BSD3
author:              "James Felix Black"
maintainer:          "j@tft.io"
copyright:           "2021 James Felix Black"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tftio/AOC2020#readme>

dependencies:
- base >= 4.7 && < 5
- split
- regex-tdfa
- sort
- containers
- raw-strings-qq
- hashmap
- vector
- text

library:
  source-dirs: src

executables:
  AOC2020-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC2020

tests:
  AOC2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC2020
